//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: storage.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Storage_StorageClient`, then call methods of this protocol to make API calls.
internal protocol Storage_StorageClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Storage_StorageClientInterceptorFactoryProtocol? { get }

  func getProfile(
    _ request: Storage_GetProfileRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Storage_GetProfileRequest, Storage_GetProfileResponse>

  func updateProfile(
    _ request: Storage_UpdateProfileRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Storage_UpdateProfileRequest, Storage_UpdateProfileResponse>
}

extension Storage_StorageClientProtocol {
  internal var serviceName: String {
    return "storage.Storage"
  }

  /// Unary call to GetProfile
  ///
  /// - Parameters:
  ///   - request: Request to send to GetProfile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getProfile(
    _ request: Storage_GetProfileRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Storage_GetProfileRequest, Storage_GetProfileResponse> {
    return self.makeUnaryCall(
      path: "/storage.Storage/GetProfile",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProfileInterceptors() ?? []
    )
  }

  /// Unary call to UpdateProfile
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateProfile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateProfile(
    _ request: Storage_UpdateProfileRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Storage_UpdateProfileRequest, Storage_UpdateProfileResponse> {
    return self.makeUnaryCall(
      path: "/storage.Storage/UpdateProfile",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? []
    )
  }
}

internal protocol Storage_StorageClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'getProfile'.
  func makeGetProfileInterceptors() -> [ClientInterceptor<Storage_GetProfileRequest, Storage_GetProfileResponse>]

  /// - Returns: Interceptors to use when invoking 'updateProfile'.
  func makeUpdateProfileInterceptors() -> [ClientInterceptor<Storage_UpdateProfileRequest, Storage_UpdateProfileResponse>]
}

internal final class Storage_StorageClient: Storage_StorageClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Storage_StorageClientInterceptorFactoryProtocol?

  /// Creates a client for the storage.Storage service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Storage_StorageClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

